(function($){
    window.travelStateGov = window.travelStateGov || {};
    travelStateGov.CountryListACS = {
        sourceData : [
            {"code":"AF","value":"Afghanistan"},
            {"code":"AL","value":"Albania"},
            {"code":"AG","value":"Algeria"},
            {"code":"AN","value":"Andorra"},
            {"code":"AO","value":"Angola"},
            {"code":"AV","value":"Anguilla"},
            {"code":"AY","value":"Antarctica","official":"Antarctica"},
            {"code":"AY","value":"South Pole","official":"Antarctica"},
            {"code":"AC","value":"Antigua and Barbuda"},
            {"code":"AR","value":"Argentina"},
            {"code":"AM","value":"Armenia"},
            {"code":"AA","value":"Aruba"},
            {"code":"AS","value":"Australia"},
            {"code":"AU","value":"Austria"},
            {"code":"AJ","value":"Azerbaijan"},
            {"code":"PO","value":"Azores"},
            {"code":"BA","value":"Bahrain"},
            {"code":"ID","value":"Bali"},
            {"code":"BG","value":"Bangladesh"},
            {"code":"BB","value":"Barbados"},
            {"code":"BO","value":"Belarus"},
            {"code":"BE","value":"Belgium"},
            {"code":"BH","value":"Belize"},
            {"code":"BN","value":"Benin"},
            {"code":"BD","value":"Bermuda"},
            {"code":"BT","value":"Bhutan"},
            {"code":"BL","value":"Bolivia"},
            {"code":"A1","value":"Bonaire, Sint Eustatius, and Saba (BES) (Dutch Caribbean)"},
            {"code":"BK","value":"Bosnia and Herzegovina (BiH)"},
            {"code":"BC","value":"Botswana"},
            {"code":"BR","value":"Brazil"},
            {"code":"VI","value":"British Virgin Islands (BVI)"},
            {"code":"BX","value":"Brunei"},
            {"code":"BU","value":"Bulgaria"},
            {"code":"UV","value":"Burkina Faso"},
            {"code":"BM","value":"Burma (Myanmar)"},
            {"code":"BY","value":"Burundi"},
            {"code":"CB","value":"Cambodia"},
            {"code":"CM","value":"Cameroon"},
            {"code":"CA","value":"Canada","official":"Canada"},
            {"code":"CA","value":"North Pole","official":"Canada"},
            {"code":"CV","value":"Cabo Verde (formerly Cape Verde)"},
            {"code":"CJ","value":"Cayman Islands"},
            {"code":"CT","value":"Central African Republic (CAR)"},
            {"code":"CD","value":"Chad"},
            {"code":"CI","value":"Chile"},
            {"code":"CH","value":"China"},
            {"code":"CO","value":"Colombia"},
            {"code":"CN","value":"Comoros"},
            {"code":"CS","value":"Costa Rica"},
            {"code":"IV","value":"Cote d'Ivoire (Ivory Coast)"},
            {"code":"HR","value":"Croatia"},
            {"code":"CU","value":"Cuba"},
            {"code":"UC","value":"Curacao"},
            {"code":"CY","value":"Cyprus"},
            {"code":"EZ","value":"Czech Republic"},
            {"code":"KN","value":"Democratic People's Republic of Korea (DPRK - North Korea)","official":"Democratic People's Republic of Korea (DPRK - North Korea)"},
            {"code":"KN","value":"North Korea","official":"Democratic People's Republic of Korea (DPRK - North Korea)"},
            {"code":"CG","value":"Democratic Republic of Congo (Kinshasa)"},
            {"code":"DA","value":"Denmark (including Greenland)"},
            {"code":"DJ","value":"Djibouti"},
            {"code":"DO","value":"Dominica"},
            {"code":"DR","value":"Dominican Republic (DR)"},
            {"code":"EC","value":"Ecuador"},
            {"code":"EG","value":"Egypt"},
            {"code":"ES","value":"El Salvador"},
            {"code":"UK","value":"England"},
            {"code":"EK","value":"Equatorial Guinea"},
            {"code":"ER","value":"Eritrea"},
            {"code":"EN","value":"Estonia"},
            {"code":"ET","value":"Ethiopia"},
            {"code":"FJ","value":"Fiji"},
            {"code":"FI","value":"Finland"},
            {"code":"FR","value":"France"},
            {"code":"A2","value":"French Guiana"},
            {"code":"FP","value":"French Polynesia (including Tahiti)"},
            {"code":"A3","value":"French West Indies (Martinique, Guadeloupe, St. Martin, St. Barthelemy)","official":"French West Indies (Martinique, Guadeloupe, St. Martin, St. Barthelemy)"},
            {"code":"A3","value":"Saint Martin","official":"French West Indies (Martinique, Guadeloupe, St. Martin, St. Barthelemy)"},
            {"code":"A3","value":"St. Martin","official":"French West Indies (Martinique, Guadeloupe, St. Martin, St. Barthelemy)"},
            {"code":"A3","value":"St Martin","official":"French West Indies (Martinique, Guadeloupe, St. Martin, St. Barthelemy)"},
            {"code":"A3","value":"Saint Barthelemy","official":"French West Indies (Martinique, Guadeloupe, St. Martin, St. Barthelemy)"},
            {"code":"A3","value":"St. Barthelemy","official":"French West Indies (Martinique, Guadeloupe, St. Martin, St. Barthelemy)"},
            {"code":"A3","value":"St Barthelemy","official":"French West Indies (Martinique, Guadeloupe, St. Martin, St. Barthelemy)"},
            {"code":"GB","value":"Gabon"},
            {"code":"GG","value":"Georgia"},
            {"code":"GM","value":"Germany"},
            {"code":"GH","value":"Ghana"},
            {"code":"UK","value":"Great Britain"},
            {"code":"UK","value":"Gibraltar"},
            {"code":"GR","value":"Greece"},
            {"code":"GJ","value":"Grenada"},
            {"code":"GT","value":"Guatemala"},
            {"code":"GV","value":"Guinea"},
            {"code":"PU","value":"Guinea-Bissau"},
            {"code":"GY","value":"Guyana"},
            {"code":"HA","value":"Haiti"},
            {"code":"HO","value":"Honduras"},
            {"code":"HK","value":"Hong Kong SAR"},
            {"code":"HU","value":"Hungary"},
            {"code":"IC","value":"Iceland"},
            {"code":"IN","value":"India"},
            {"code":"ID","value":"Indonesia"},
            {"code":"IR","value":"Iran"},
            {"code":"IZ","value":"Iraq"},
            {"code":"EI","value":"Ireland"},
            {"code":"IS","value":"Israel"},
            {"code":"IS","value":"Gaza"},
            {"code":"IS","value":"The West Bank"},
            {"code":"IT","value":"Italy"},
            {"code":"JM","value":"Jamaica"},
            {"code":"JA","value":"Japan"},
            {"code":"IS","value":"Jerusalem"},
            {"code":"JO","value":"Jordan"},
            {"code":"KZ","value":"Kazakhstan"},
            {"code":"KE","value":"Kenya"},
            {"code":"KR","value":"Kiribati"},
            {"code":"KV","value":"Kosovo"},
            {"code":"KU","value":"Kuwait"},
            {"code":"KG","value":"The Kyrgyz Republic"},
            {"code":"LA","value":"Laos"},
            {"code":"LG","value":"Latvia"},
            {"code":"LE","value":"Lebanon"},
            {"code":"LT","value":"Lesotho"},
            {"code":"LI","value":"Liberia"},
            {"code":"LY","value":"Libya"},
            {"code":"LS","value":"Liechtenstein"},
            {"code":"LH","value":"Lithuania"},
            {"code":"LU","value":"Luxembourg"},
            {"code":"MC","value":"Macau SAR"},
            {"code":"MK","value":"Macedonia"},
            {"code":"MA","value":"Madagascar"},
            {"code":"PO","value":"Madeira"},
            {"code":"MI","value":"Malawi"},
            {"code":"MY","value":"Malaysia"},
            {"code":"MV","value":"Maldives"},
            {"code":"ML","value":"Mali"},
            {"code":"MT","value":"Malta"},
            {"code":"MR","value":"Mauritania"},
            {"code":"MP","value":"Mauritius"},
            {"code":"MX","value":"Mexico"},
            {"code":"FM","value":"Micronesia"},
            {"code":"MD","value":"Moldova"},
            {"code":"MN","value":"Monaco"},
            {"code":"MG","value":"Mongolia"},
            {"code":"MJ","value":"Montenegro"},
            {"code":"MH","value":"Montserrat"},
            {"code":"MO","value":"Morocco"},
            {"code":"MZ","value":"Mozambique"},
            {"code":"WA","value":"Namibia"},
            {"code":"NR","value":"Nauru"},
            {"code":"NP","value":"Nepal"},
            {"code":"NC","value":"New Caledonia"},
            {"code":"NZ","value":"New Zealand"},
            {"code":"NU","value":"Nicaragua"},
            {"code":"NG","value":"Niger"},
            {"code":"NI","value":"Nigeria"},
            {"code":"UK","value":"Northern Ireland"},
            {"code":"NO","value":"Norway"},
            {"code":"MU","value":"Oman"},
            {"code":"PK","value":"Pakistan"},
            {"code":"PS","value":"Palau"},
            {"code":"PM","value":"Panama"},
            {"code":"PP","value":"Papua New Guinea (PNG)"},
            {"code":"PA","value":"Paraguay"},
            {"code":"PE","value":"Peru"},
            {"code":"RP","value":"Philippines"},
            {"code":"PL","value":"Poland"},
            {"code":"PO","value":"Portugal"},
            {"code":"QA","value":"Qatar"},
            {"code":"CF","value":"Republic of Congo (Brazzaville)"},
            {"code":"KS","value":"Republic of Korea (RoK - South Korea)"},
            {"code":"RM","value":"Republic of the Marshall Islands"},
            {"code":"RO","value":"Romania"},
            {"code":"RS","value":"Russia"},
            {"code":"RW","value":"Rwanda"},
            {"code":"SC","value":"Saint Kitts and Nevis","official":"Saint Kitts and Nevis"},
            {"code":"SC","value":"St. Kitts and Nevis","official":"Saint Kitts and Nevis"},
            {"code":"SC","value":"St Kitts and Nevis","official":"Saint Kitts and Nevis"},
            {"code":"ST","value":"Saint Lucia","official":"Saint Lucia"},
            {"code":"ST","value":"St. Lucia","official":"Saint Lucia"},
            {"code":"ST","value":"St Lucia","official":"Saint Lucia"},
            {"code":"VC","value":"Saint Vincent and the Grenadines","official":"Saint Vincent and the Grenadines"},
            {"code":"VC","value":"St. Vincent and the Grenadines","official":"Saint Vincent and the Grenadines"},
            {"code":"VC","value":"St Vincent and the Grenadines","official":"Saint Vincent and the Grenadines"},
            {"code":"WS","value":"Samoa"},
            {"code":"SM","value":"San Marino"},
            {"code":"TP","value":"Sao Tome and Principe"},
            {"code":"SA","value":"Saudi Arabia"},
            {"code":"UK","value":"Scotland"},
            {"code":"SG","value":"Senegal"},
            {"code":"RI","value":"Serbia"},
            {"code":"SE","value":"Seychelles"},
            {"code":"SL","value":"Sierra Leone"},
            {"code":"SN","value":"Singapore"},
            {"code":"NN","value":"Sint Maarten","official":"Sint Maarten"},
            {"code":"NN","value":"St. Maarten","official":"Sint Maarten"},
            {"code":"NN","value":"St Maarten","official":"Sint Maarten"},
            {"code":"NN","value":"Saint Maarten","official":"Sint Maarten"},
            {"code":"LO","value":"Slovakia"},
            {"code":"SI","value":"Slovenia"},
            {"code":"BP","value":"Solomon Islands"},
            {"code":"SO","value":"Somalia"},
            {"code":"SF","value":"South Africa"},
            {"code":"OD","value":"South Sudan"},
            {"code":"SP","value":"Spain"},
            {"code":"CE","value":"Sri Lanka"},
            {"code":"SU","value":"Sudan"},
            {"code":"NS","value":"Suriname"},
            {"code":"WZ","value":"Swaziland"},
            {"code":"SW","value":"Sweden"},
            {"code":"SZ","value":"Switzerland"},
            {"code":"SY","value":"Syria"},
            {"code":"TW","value":"Taiwan"},
            {"code":"TI","value":"Tajikistan"},
            {"code":"TZ","value":"Tanzania"},
            {"code":"TZ","value":"Zanzibar"},
            {"code":"TH","value":"Thailand"},
            {"code":"BF","value":"The Bahamas"},
            {"code":"GA","value":"The Gambia"},
            {"code":"NL","value":"The Netherlands (Holland)"},
            {"code":"TT","value":"Timor-Leste (East Timor)"},
            {"code":"TO","value":"Togo"},
            {"code":"TN","value":"Tonga"},
            {"code":"TD","value":"Trinidad and Tobago"},
            {"code":"TS","value":"Tunisia"},
            {"code":"TU","value":"Turkey"},
            {"code":"TX","value":"Turkmenistan"},
            {"code":"TK","value":"Turks and Caicos"},
            {"code":"TV","value":"Tuvalu"},
            {"code":"UG","value":"Uganda"},
            {"code":"UP","value":"Ukraine"},
            {"code":"AE","value":"United Arab Emirates (UAE)"},
            {"code":"UK","value":"United Kingdom (UK)"},
            {"code":"UY","value":"Uruguay"},
            {"code":"UZ","value":"Uzbekistan"},
            {"code":"NH","value":"Vanuatu"},
            {"code":"VT","value":"Vatican City (Holy See)"},
            {"code":"VE","value":"Venezuela"},
            {"code":"VM","value":"Vietnam"},
            {"code":"UK","value":"Wales"},
            {"code":"YM","value":"Yemen"},
            {"code":"ZA","value":"Zambia"},
            {"code":"ZI","value":"Zimbabwe"}
        ]
    };
})(jQuery);